@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Aug 03 17:15:31 +0300 2025
REM SW Build 5239630 on Fri Nov 08 22:35:27 MST 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim top_encryption_tb_behav -key {Behavioral:sim_1:Functional:top_encryption_tb} -tclbatch top_encryption_tb.tcl -view D:/Vivado documents/AES_CTR_Encryption_Decryption/aes_ctr_core_pipelined/tb_key_expansion_behav2.wcfg -log simulate.log"
call xsim  top_encryption_tb_behav -key {Behavioral:sim_1:Functional:top_encryption_tb} -tclbatch top_encryption_tb.tcl -view D:/Vivado documents/AES_CTR_Encryption_Decryption/aes_ctr_core_pipelined/tb_key_expansion_behav2.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
